return {
	dark = {
		black = "#000000",
		bg0 = "#2b203f", -- editor.background
		bg1 = "#292239", -- editorPane.background
		bg2 = "#393050", -- editor.lineHighlightBackground
		bg3 = "#393050",
		bg_d = "#1d142e", -- sideBar.background
		bg_blue = "#5d37e6", -- editorOverviewRuler.addedForeground
		bg_yellow = "#d6bc83", -- editorGutter.modifiedBackground
		fg = "#c0bbcb", -- foreground
		purple = "#c07cff", -- "Function parameter"
		green = "#63ee92", -- "Property value" -- missing color
		orange = "#b573b4", -- "Constant" -- wrong color
		blue = "#c7a8ed", -- "Keyword" -- wrong color
		yellow = "#e6be7d", -- "Strings"
		cyan = "#79cfb3", -- gitDecoration.untrackedResourceForeground
		red = "#e678e8", -- "Function name, class name, new class expression."
		grey = "#73688d", -- "Comments"
		light_grey = "#ada2c8", -- editorLineNumber.activeForeground
		dark_cyan = "#375de6", -- "[Diff] Header"
		dark_red = "#fa3d7c", -- editorOverviewRuler.warningForeground
		dark_yellow = "#b573b4", -- "Constant" -- wrong color
		dark_purple = "#a37cff", -- "Attribute name" -- missing color
		diff_add = "#96bd65", -- "[Diff] Inserted"
		diff_delete = "#d36666", -- "[Diff] Deleted"
		diff_change = "#e0bc58", -- "[Diff] Inserted"
		diff_text = "#375de6", -- "[Diff] Header"
	},
	slate = {
		black = "#000000",
		bg0 = "#1c1c1d", -- editor.background
		bg1 = "#222223", -- editorPane.background
		bg2 = "#2a2a2e", -- editor.lineHighlightBackground
		bg3 = "#2a2a2e",
		bg_d = "#141414", -- sideBar.background
		bg_blue = "#876ee2", -- editorOverviewRuler.addedForeground
		bg_yellow = "#c5a36b", -- editorGutter.modifiedBackground
		fg = "#aba6b5", -- foreground
		purple = "#9d8eff", -- "Function parameter"
		green = "#63ee92", -- "Property value" -- missing color
		orange = "#b573b4", -- "Constant" -- wrong color
		blue = "#bfbbcd", -- "Keyword" -- wrong color
		yellow = "#c9a974", -- "Strings"
		cyan = "#79cfb3", -- gitDecoration.untrackedResourceForeground
		red = "#c776dd", -- "Function name, class name, new class expression." -- wrong color
		grey = "#797782", -- "Comments"
		light_grey = "#d6d2eb", -- editorLineNumber.activeForeground
		dark_cyan = "#375de6", -- "[Diff] Header"
		dark_red = "#f070a3", -- editorOverviewRuler.warningForeground
		dark_yellow = "#b573b4", -- "Constant" -- wrong color
		dark_purple = "#a37cff", -- "Attribute name" -- missing color
		diff_add = "#96bd65", -- "[Diff] Inserted"
		diff_delete = "#d36666", -- "[Diff] Deleted"
		diff_change = "#e0bc58", -- "[Diff] Inserted"
		diff_text = "#375de6", -- "[Diff] Header"
	},
	violet = {
		black = "#000000",
		bg0 = "#241e3d", -- editor.background
		bg1 = "#2d2b49", -- editorPane.background
		bg2 = "#3d3552", -- editor.lineHighlightBackground
		bg3 = "#3d3552",
		bg_d = "#19152a", -- sideBar.background
		bg_blue = "#5d37e6", -- editorOverviewRuler.addedForeground
		bg_yellow = "#d1b959", -- editorGutter.modifiedBackground
		fg = "#c0bbcb", -- foreground
		purple = "#c884ff", -- "Function parameter"
		green = "#63ee92", -- "Property value"
		orange = "#f8a066", -- "Constant"
		blue = "#8087ee", -- "Keyword"
		yellow = "#ddb672", -- "Strings"
		cyan = "#75bcff", -- gitDecoration.untrackedResourceForeground
		red = "#fe719e", -- "Function name, class name, new class expression."
		grey = "#7f729c", -- "Comments"
		light_grey = "#a8a2c8", -- editorLineNumber.activeForeground
		dark_cyan = "#375de6", -- "[Diff] Header"
		dark_red = "#fa3d7c", -- editorOverviewRuler.warningForeground
		dark_yellow = "#f8a066", -- "Constant"
		dark_purple = "#a37cff", -- "Attribute name"
		diff_add = "#96bd65", -- "[Diff] Inserted"
		diff_delete = "#d36666", -- "[Diff] Deleted"
		diff_change = "#e0bc58", -- "[Diff] Inserted"
		diff_text = "#375de6", -- "[Diff] Header"
	},
}
